### ISSUE TITLE
Missing test data

### ISSUE THREAD

**Issue by bjlittle** [NESII/conda-esmf#1]
Awesome work Ben!  

Thanks for creating this conda recipe. Made my life super easy.

Needs a minor tweak to include the esmpy test data so that all the tests work and pass.

There's also a testing esmpy .txt file missing, which Ryan knows about ... Sorry about the lack of exact details 😉

So far otherwise :+1:

P.S. You know about https://binstar.org/asmeurer/gcc, right?

**Comment by bekozi** [comment]
Glad it helped! I had not seen that gcc package, so definitely thanks for that. I'll work with Ryan to get the esmpy test suite running.

**Comment by bjlittle** [comment]
Cheers :beers:

**Comment by bekozi** [comment]
Tests for ESMPy are run appropriately during the build for 6.3.0rp1 and 7.x. Let me know if you find otherwise!
